services:
  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ledgersignal
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: ledgersignal
    volumes:
      - pgdata:/var/lib/postgresql/data

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: linkvault-redpanda
    command:
      - redpanda
      - start
      - --smp=1
      - --memory=512M
      - --overprovisioned
      - --node-id=0
      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr=internal://redpanda:9092,external://localhost:19092
      - --rpc-addr=redpanda:33145
      - --advertise-rpc-addr=redpanda:33145
    ports:
      - "19092:19092"
      - "9644:9644"
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD", "rpk", "cluster", "health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pgdata:
  redpanda_data: